version: '3'
services:
  postgres:
    image: postgres:latest

  redis:
    image: redis:latest

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server

    volumes:
      - /app/node_modules
      - ./server:/app

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client

    volumes:
      - /app/node_module
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./client

    volumes:
      - /app/node_module
      - ./client:/app

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev

    ports:
      - 3001:80
